# -*- coding: utf-8 -*-
"""Untitled46.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ss6kIUsuupZMaKDoeg37nBrxwknL8xsV
"""

# -*- coding: utf-8 -*-
"""SingleMailSend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BX2lZTX0d57gcNb_gmAQVLKiI0jatyND
"""

#File name:mimiAndMeSingleMailSend
import smtplib
import random
from datetime import datetime

now = datetime.now()

# Random Texts to be sent
texts = [
    "Hey mimi moy iloveyou :(",
    "Matakia mou sou euxomai kalh mera na exeis :P)",
    "Prinsaki mou Fluffy i love youuuuuuuu",
    "Thelw na se dw agaph mou, mou eleipses:(",
    "Sagapaw mimi mou, pare me thlefwno soon na milhsoume",
    "Kalh mera na exeis mimaki mou panemorfo",
    "Exw thn pio kouklara gamw to spiti m gamw",
    "POIO EINAI TO MIMAKI MOUUUU????? :)))",
    "Plats plouts phga toualeta kai epese mesa kai ekane plats plouts..",
    "Den tha se allaza me tipota. Ela omorfes kalhmeres.",
    "Ton kafe moy metrio kai thn alhtheia sketh. Kalhmera.",
    "Mimi an blepeis auto to mnma tote soy xrwstaw tirkouaz terrea(An den sou phre o deliveras..)",
    "Surprise its me mimi again goodmorning ma babygerllll",
    "Kalhmera Kokla moy soy fernw amesws kafe!!",
    "Kafe louloudia kai terrea gia to mimi mou amesws!!!!!",
    "Kala e pws niwtheis pou exeis ton pio kouklo gamw??",
    "Elpizw na mhn exeis nteliverades shmera konta sou:((",
    "Hey mimi an me agapas steile moy ena mnma na xarw",
    "An sou milhsei kaneis shmera tha skasw me to elikoptero to katalaves mwrh?",
    "haha shmera paw na sou parw to dwwwrooo alla den tseresi esu giati tha to deis allh mera to mail hihi",
    "Heeeeey mimi mou goodmorning",
    "Tha se parakolouthw shmera ;)",
    "Iou pws eisai etsi",
    "-Egw (se vlepw)   -Epishs egw: AAAAAAAAAAAAAAA",
    "Kalimera koyklara mou ante ante tsipna pame !",
    "Kalimera, moro mou.Aplo kai lito ante polla thes",
    "eeeeeii(me glukia fwnh) Tsipna ypnarou tsipna!",
    "Na pas stous gkomenous sou den exei kalimera.",
    "Etoimasou k ela edw twra. Se perimenw:(",
    "Glykoula mou thes kafe k terrea?.",
    "Pws eisai etsi re upnara bgale tis tsimples sou.",
    "Den exw janadei pio wraio pithikaki;)",
    "Entajei arketa kala mail esu den kaneis tipota gia mena(Thelw prosoxi)",
    "Agaph mou o kosmos einai asxhmos epeidh uparxeis esy.",
    "Skase",
    "SSSSSSSSSSSSSSS!!",
    "sssssssssssssssssssss",
    "Ena filaki gia na tsekinisei sosta i mera sou .",
    "Ekso exei ilio, alla to xamogelo sou einai pio foteino!haha ti lew re malaka",
    "Mia ypenthymisi gia to proi: pws eisai etsi gamw to spiti mou gamw.",
    "I zoi mou einai kalyteri apo ti stigmi pou mpikes mesa.Alla tha einai akoma kaluterh otan janampw egw mesa sou",
    "Kathe mera pou xypnaw, skeftomai poso tyxeros eimai… pou den se pantreuthka akoma.",
    "Pos tha kyllisei simera? O,ti ki an kaneis, eimai dipla sou.",
    "I am boss."
]


#SEND TO MIMI
email = "agapwtomimimou@gmail.com"
receiver_email = "nagiagiannousa165@gmail.com" #nagiagiannousa165@gmail.com
subject = "Exete Mail apo to mimi sas:"
message = random.choice(texts)  # Randomly select a text

text = f"Subject: {subject}\n\n{message}"

server = smtplib.SMTP('smtp.gmail.com', 587)
server.ehlo()
server.starttls()  # Secure the connection
server.login(email, "jlxz xmkp eaxb mbwr")
server.sendmail(email, receiver_email, text)
print(f'Mail to nagiagiannousa165@gmail.com sent at {now.strftime("%H:%M:%S")}')

server.quit()



#SEND TO MWKOS
email = "agapwtomimimou@gmail.com"
receiver_email = "mwkospanagiotis@gmail.com" #mwkospanagiotis@gmail.com
subject = "GitHub Commit Reminder"
message = "Kane Git Commit"

text = f"Subject: {subject}\n\n{message}"

server = smtplib.SMTP('smtp.gmail.com', 587)
server.ehlo()
server.starttls()  # Secure the connection
server.login(email, "jlxz xmkp eaxb mbwr")
server.sendmail(email, receiver_email, text)
print(f'Mail to mwkospanagiotis@gmail.com sent at {now.strftime("%H:%M:%S")}')

server.quit()